extern const GeoLayout trollstair_geo[];
extern Lights1 trollstair_diamond_plate_shaded_lights;
extern Lights1 trollstair_Metal_lights;
extern u8 trollstair_diamond_plate_i8[];
extern u8 trollstair_Metal_ReinforcedGridWall_ci8[];
extern u8 trollstair_Metal_ReinforcedGridWall_pal_rgba16[];
extern Vtx trollstair_Plane_004_mesh_layer_1_vtx_0[8];
extern Gfx trollstair_Plane_004_mesh_layer_1_tri_0[];
extern Vtx trollstair_Plane_004_mesh_layer_1_vtx_1[12];
extern Gfx trollstair_Plane_004_mesh_layer_1_tri_1[];
extern Gfx mat_trollstair_diamond_plate_shaded[];
extern Gfx mat_trollstair_Metal[];
extern Gfx mat_revert_trollstair_Metal[];
extern Gfx trollstair_Plane_004_mesh_layer_1[];
extern Gfx trollstair_material_revert_render_settings[];
