extern const GeoLayout creepie_door_geo[];
extern u8 creepie_door_door_ci8[];
extern u8 creepie_door_door_pal_rgba16[];
extern u8 creepie_door_rgba16_anonmoose_envmap_silver1_i8[];
extern Vtx creepie_door_000_offset_001_mesh_layer_1_vtx_0[56];
extern Gfx creepie_door_000_offset_001_mesh_layer_1_tri_0[];
extern Vtx creepie_door_000_offset_001_mesh_layer_1_vtx_1[52];
extern Gfx creepie_door_000_offset_001_mesh_layer_1_tri_1[];
extern Gfx mat_creepie_door_door[];
extern Gfx mat_revert_creepie_door_door[];
extern Gfx mat_creepie_door_goldknob[];
extern Gfx mat_revert_creepie_door_goldknob[];
extern Gfx creepie_door_000_offset_001_mesh_layer_1[];
extern Gfx creepie_door_material_revert_render_settings[];
