extern const GeoLayout tl_logo_geo[];
extern u8 tl_logo_troll_lab_logo_ia8[];
extern u8 tl_logo_lab_goo_i8[];
extern Vtx tl_logo_Plane_mesh_layer_1_vtx_0[212];
extern Gfx tl_logo_Plane_mesh_layer_1_tri_0[];
extern Vtx tl_logo_Plane_mesh_layer_1_vtx_1[149];
extern Gfx tl_logo_Plane_mesh_layer_1_tri_1[];
extern Gfx mat_tl_logo_troll_lab_logo[];
extern Gfx mat_tl_logo_lab_goo[];
extern Gfx mat_revert_tl_logo_lab_goo[];
extern Gfx tl_logo_Plane_mesh_layer_1[];
extern Gfx tl_logo_material_revert_render_settings[];
