extern const GeoLayout tl_logo2_geo[];
extern u8 tl_logo2_troll_lab_logo_i8[];
extern u8 tl_logo2_lab_goo_i8[];
extern Vtx tl_logo2_Plane_mesh_layer_1_vtx_0[182];
extern Gfx tl_logo2_Plane_mesh_layer_1_tri_0[];
extern Vtx tl_logo2_Plane_mesh_layer_1_vtx_1[138];
extern Gfx tl_logo2_Plane_mesh_layer_1_tri_1[];
extern Gfx mat_tl_logo2_troll_lab_logo[];
extern Gfx mat_tl_logo2_lab_goo_layer1[];
extern Gfx mat_revert_tl_logo2_lab_goo_layer1[];
extern Gfx tl_logo2_Plane_mesh_layer_1[];
extern Gfx tl_logo2_material_revert_render_settings[];
