#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "make_const_nonconst.h"

#include "common1.h"
#include "group0.h"

#include "bubble/geo.inc.c"
#include "walk_smoke/geo.inc.c"
#include "burn_smoke/geo.inc.c"
#include "small_water_splash/geo.inc.c"
#include "water_wave/geo.inc.c"
#include "sparkle/geo.inc.c"
#include "water_splash/geo.inc.c"
#include "sparkle_animation/geo.inc.c"
#include "mario/geo.inc.c"
#include "moneybag/geo.inc.c"

#include "Hammerbro/geo.inc.c"
#include "hammer/geo.inc.c"
#include "ring/geo.inc.c"
#include "metal_crate/geo.inc.c"
#include "monty_mole/geo.inc.c"
#include "chicken/geo.inc.c"
#include "token/geo.inc.c"
#include "egg/geo.inc.c"
#include "snakeblock1/geo.inc.c"
#include "snakeblock2/geo.inc.c"
#include "snakeblock3/geo.inc.c"
#include "Rex/geo.inc.c"
#include "dcoin/geo.inc.c"
#include "wallet/geo.inc.c"
#include "noteblock/geo.inc.c"
#include "billmask/geo.inc.c"
#include "showrunner/geo.inc.c"
#include "spotlight/geo.inc.c"

#include "tvhead/geo.inc.c"
#include "quest/geo.inc.c"
#include "rocket_boot/geo.inc.c"
#include "vanetalc/geo.inc.c"
#include "ocean_ttc/geo.inc.c"
#include "tvcorpse/geo.inc.c"
#include "cosmic_spike/geo.inc.c"
#include "crowbar2/geo.inc.c"
#include "a_fast/geo.inc.c"
#include "a_pingas/geo.inc.c"

#include "tl_logo2/geo.inc.c"
#include "troll_element/geo.inc.c"
#include "killerspikes/geo.inc.c"
#include "global_cone/geo.inc.c"
#include "aford/geo.inc.c"
#include "voidleak/geo.inc.c"
#include "checkpoint_flag/geo.inc.c"
#include "monitor/geo.inc.c"