extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern u8 bob_dl_ConcreteTileClean_i8[];
extern Vtx bob_dl_Circle_mesh_layer_5_vtx_cull[8];
extern Vtx bob_dl_Circle_mesh_layer_5_vtx_0[134];
extern Gfx bob_dl_Circle_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Circle_001_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Circle_001_mesh_layer_1_vtx_0[20];
extern Gfx bob_dl_Circle_001_mesh_layer_1_tri_0[];
extern Gfx mat_bob_dl_CleanConcreteGrid[];
extern Gfx mat_revert_bob_dl_CleanConcreteGrid[];
extern Gfx mat_bob_dl_CleanConcreteGrid_001[];
extern Gfx mat_revert_bob_dl_CleanConcreteGrid_001[];
extern Gfx bob_dl_Circle_mesh_layer_5[];
extern Gfx bob_dl_Circle_001_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
