extern const GeoLayout quarantine_geo[];
extern Lights1 quarantine_QuaratineDoor_lights;
extern u8 quarantine_QUARANTINE_rgba16[];
extern u8 quarantine_Concrete_ci4[];
extern u8 quarantine_Concrete_pal_rgba16[];
extern Vtx quarantine_Cube_003_mesh_layer_1_vtx_0[92];
extern Gfx quarantine_Cube_003_mesh_layer_1_tri_0[];
extern Vtx quarantine_Cube_003_mesh_layer_1_vtx_1[12];
extern Gfx quarantine_Cube_003_mesh_layer_1_tri_1[];
extern Gfx mat_quarantine_QuaratineDoor[];
extern Gfx mat_quarantine_Concrete[];
extern Gfx mat_revert_quarantine_Concrete[];
extern Gfx quarantine_Cube_003_mesh_layer_1[];
extern Gfx quarantine_material_revert_render_settings[];
