extern const GeoLayout pillar_troll_geo[];
extern Lights1 pillar_troll_trollge_lights;
extern Lights1 pillar_troll_white_lights;
extern u8 pillar_troll_trollge_i8[];
extern Vtx pillar_troll_Cube_005_mesh_layer_1_vtx_0[87];
extern Gfx pillar_troll_Cube_005_mesh_layer_1_tri_0[];
extern Vtx pillar_troll_Cube_005_mesh_layer_1_vtx_1[97];
extern Gfx pillar_troll_Cube_005_mesh_layer_1_tri_1[];
extern Vtx pillar_troll_Cube_005_mesh_layer_1_vtx_2[157];
extern Gfx pillar_troll_Cube_005_mesh_layer_1_tri_2[];
extern Gfx mat_pillar_troll_trollge[];
extern Gfx mat_pillar_troll_white[];
extern Gfx mat_pillar_troll_blackoutline[];
extern Gfx pillar_troll_Cube_005_mesh_layer_1[];
extern Gfx pillar_troll_material_revert_render_settings[];
