extern const GeoLayout hmc_area_1_geo[];
extern const GeoLayout hmc_area_1[];
extern const Collision hmc_area_1_collision[];
extern const MacroObject hmc_area_1_macro_objs[];
extern u8 hmc_dl_SandCanyon_ci8[];
extern u8 hmc_dl_SandCanyon_pal_rgba16[];
extern u8 hmc_dl_Mesa_rgba16[];
extern u8 hmc_dl_another_multitex_i4[];
extern Vtx hmc_dl_lvl_mesh_layer_1_vtx_0[113];
extern Gfx hmc_dl_lvl_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_lvl_mesh_layer_1_vtx_1[367];
extern Gfx hmc_dl_lvl_mesh_layer_1_tri_1[];
extern Vtx hmc_dl_lvl_mesh_layer_5_vtx_0[168];
extern Gfx hmc_dl_lvl_mesh_layer_5_tri_0[];
extern Gfx mat_hmc_dl_Sand_002[];
extern Gfx mat_revert_hmc_dl_Sand_002[];
extern Gfx mat_hmc_dl_Mesa_001_layer1[];
extern Gfx mat_revert_hmc_dl_Mesa_001_layer1[];
extern Gfx mat_hmc_dl_MesaTransparent_layer5[];
extern Gfx mat_revert_hmc_dl_MesaTransparent_layer5[];
extern Gfx hmc_dl_lvl_mesh_layer_1[];
extern Gfx hmc_dl_lvl_mesh_layer_5[];
extern Gfx hmc_dl_material_revert_render_settings[];
