extern const GeoLayout hmc_area_1_geo[];
extern const GeoLayout hmc_area_1[];
extern const Collision hmc_area_1_collision[];
extern const MacroObject hmc_area_1_macro_objs[];
extern Lights1 hmc_dl_f3dlite_material_lights;
extern u8 hmc_dl_SandCanyon_ci8[];
extern u8 hmc_dl_SandCanyon_pal_rgba16[];
extern u8 hmc_dl_Mesa_rgba16[];
extern u8 hmc_dl_another_multitex_i4[];
extern u8 hmc_dl_Cactus_rgba16[];
extern u8 hmc_dl_metal_wall_ci8[];
extern u8 hmc_dl_metal_wall_pal_rgba16[];
extern Vtx hmc_dl_decor_mesh_layer_1_vtx_0[189];
extern Gfx hmc_dl_decor_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_lvl_mesh_layer_1_vtx_0[358];
extern Gfx hmc_dl_lvl_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_lvl_mesh_layer_1_vtx_1[1199];
extern Gfx hmc_dl_lvl_mesh_layer_1_tri_1[];
extern Vtx hmc_dl_lvl_mesh_layer_1_vtx_2[1215];
extern Gfx hmc_dl_lvl_mesh_layer_1_tri_2[];
extern Vtx hmc_dl_lvl_mesh_layer_1_vtx_3[353];
extern Gfx hmc_dl_lvl_mesh_layer_1_tri_3[];
extern Vtx hmc_dl_lvl_mesh_layer_5_vtx_0[320];
extern Gfx hmc_dl_lvl_mesh_layer_5_tri_0[];
extern Gfx mat_hmc_dl_f3dlite_material[];
extern Gfx mat_hmc_dl_Sand_002[];
extern Gfx mat_revert_hmc_dl_Sand_002[];
extern Gfx mat_hmc_dl_Mesa_001_layer1[];
extern Gfx mat_revert_hmc_dl_Mesa_001_layer1[];
extern Gfx mat_hmc_dl_MesaTransparent_layer5[];
extern Gfx mat_revert_hmc_dl_MesaTransparent_layer5[];
extern Gfx mat_hmc_dl_Cactus[];
extern Gfx mat_revert_hmc_dl_Cactus[];
extern Gfx mat_hmc_dl_metalfoil[];
extern Gfx mat_revert_hmc_dl_metalfoil[];
extern Gfx hmc_dl_decor_mesh_layer_1[];
extern Gfx hmc_dl_lvl_mesh_layer_1[];
extern Gfx hmc_dl_lvl_mesh_layer_5[];
extern Gfx hmc_dl_material_revert_render_settings[];
