extern const GeoLayout connex1_geo[];
extern u8 connex1_connex_door_i4[];
extern u8 connex1_connex_i4[];
extern Vtx connex1_viscol_002_mesh_layer_1_vtx_0[8];
extern Gfx connex1_viscol_002_mesh_layer_1_tri_0[];
extern Vtx connex1_viscol_002_mesh_layer_1_vtx_1[12];
extern Gfx connex1_viscol_002_mesh_layer_1_tri_1[];
extern Gfx mat_connex1_connex_door_orange_layer1[];
extern Gfx mat_revert_connex1_connex_door_orange_layer1[];
extern Gfx mat_connex1_connex_orange_layer1[];
extern Gfx mat_revert_connex1_connex_orange_layer1[];
extern Gfx connex1_viscol_002_mesh_layer_1[];
extern Gfx connex1_material_revert_render_settings[];
