extern const GeoLayout castle_inside_area_1_geo[];
extern const GeoLayout castle_inside_area_1[];
extern const Collision castle_inside_area_1_collision[];
extern const MacroObject castle_inside_area_1_macro_objs[];
extern u8 castle_inside_dl_ConcreteTileClean_i8[];
extern u8 castle_inside_dl_warning_mirror_rgba16[];
extern Vtx castle_inside_dl_aa_place1_mesh_layer_1_vtx_0[17];
extern Gfx castle_inside_dl_aa_place1_mesh_layer_1_tri_0[];
extern Vtx castle_inside_dl_aa_place1_mesh_layer_1_vtx_1[31];
extern Gfx castle_inside_dl_aa_place1_mesh_layer_1_tri_1[];
extern Vtx castle_inside_dl_ac_z_mesh_layer_1_vtx_0[8];
extern Gfx castle_inside_dl_ac_z_mesh_layer_1_tri_0[];
extern Vtx castle_inside_dl_decal_mesh_layer_4_vtx_cull[8];
extern Vtx castle_inside_dl_decal_mesh_layer_4_vtx_0[30];
extern Gfx castle_inside_dl_decal_mesh_layer_4_tri_0[];
extern Vtx castle_inside_dl_Regular_geometry_mesh_layer_1_vtx_0[43];
extern Gfx castle_inside_dl_Regular_geometry_mesh_layer_1_tri_0[];
extern Gfx mat_castle_inside_dl_CleanConcreteGrid[];
extern Gfx mat_revert_castle_inside_dl_CleanConcreteGrid[];
extern Gfx mat_castle_inside_dl_z_buffer_only_layer1[];
extern Gfx mat_revert_castle_inside_dl_z_buffer_only_layer1[];
extern Gfx mat_castle_inside_dl_mirrorwarning[];
extern Gfx castle_inside_dl_aa_place1_mesh_layer_1[];
extern Gfx castle_inside_dl_ac_z_mesh_layer_1[];
extern Gfx castle_inside_dl_decal_mesh_layer_4[];
extern Gfx castle_inside_dl_Regular_geometry_mesh_layer_1[];
extern Gfx castle_inside_dl_material_revert_render_settings[];
